package com.shopallday.storage.domain.exceptions;

public enum BusinessErrorCodes {
    CUSTOMER_NOT_FOUND,
    CUSTOMER_COULD_NOT_BE_CREATED,
    CUSTOMER_ALREADY_EXISTS,
    CUSTOMER_COULD_NOT_BE_UPDATED,
    CUSTOMER_COULD_NOT_BE_DELETED,
    PRODUCT_COULD_NOT_BE_CREATED,
    PRODUCT_COULD_NOT_BE_DELETED,
    PRODUCT_COULD_NOT_BE_UPDATED,
    PRODUCT_NOT_FOUND,
    PRODUCT_TYPE_NOT_FOUND,
    CATEGORY_COULD_NOT_BE_CREATED,
    CATEGORY_COULD_NOT_BE_DELETED,
    CATEGORY_COULD_NOT_BE_UPDATED,
    CATEGORY_NOT_FOUND,
    BRAND_COULD_NOT_BE_CREATED,
    BRAND_COULD_NOT_BE_DELETED,
    BRAND_COULD_NOT_BE_UPDATED,
    BRAND_NOT_FOUND,
}
