version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!
    networks:
      - db-network

  storage_app:
#    If we want to use a pre-built image, uncomment and comment out the below build
#    image: storage-app:latest
    build:
      context: storage-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
