version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_DB: storeage-db
    networks:
      - db-network
    hostname: db  # Specify the hostname for the PostgreSQL service

  storage_app:
    build:
      context: storage-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
